import { createContext, useContext, useEffect, type ReactNode } from "react";
import type { CatalogLocale } from "../../types/catalog";

export const translations = {
  en: {
    all: "All", officialShop: "Official Shop", boothInfo: "Booth info", boothInfoHint: "Hours, location & socials",
    searchItems: "Search items...", searchCatalog: "Search catalog", clearSearch: "Clear search", recommended: "Recommended",
    priceLow: "Price ↑", priceHigh: "Price ↓", mostStock: "Most stock", name: "Name", gridView: "Grid view", listView: "List view", previousCategories: "Previous categories", nextCategories: "More categories",
    featuredDrop: "Featured drop", limitedCollection: "Limited collection", specialRelease: "A special booth release available while stock lasts.", noFeatured: "No featured drop yet", noFeaturedHint: "The booth’s hand-picked releases will appear here.",
    inStock: "In stock", onlyLeft: (count: number) => `Only ${count} left`, addToCart: "Add to cart", swipeToBrowse: "Swipe to browse",
    featured: "Featured", sale: "Sale", soldOut: "Sold out", available: (count: number) => `${count} available`, unavailable: "Unavailable",
    viewDetails: (name: string) => `View details for ${name}`, addProduct: (name: string) => `Add ${name} to cart`, productSoldOut: (name: string) => `${name} is sold out`,
    cart: "Cart", emptyCart: "Your cart is empty", emptyCartHint: "Tap merch cards to add items to the cart.", viewCart: "View cart", clearAll: "Clear all", cartDockTitle: (count: number) => `${count} ${count === 1 ? "item" : "items"} ready in your cart`, cartDockHint: "Your cart stays nearby while you browse.",
    totalPrice: "Total price", payNow: "Pay now", itemDetails: "Item details", featuredItem: "Featured item", item: "Item", price: "Price", discount: "Promotion discount",
    buyXGetY: (buy: number, free: number) => `Buy ${buy}, get ${free} free`, qualifyingPromotion: (buy: number) => `Counts toward Buy ${buy}`, rewardPromotion: "Free reward option", combinedPromotion: (buy: number, free: number) => `Buy ${buy}, choose ${free} free`, freeItems: (count: number) => `${count} free`, promotionApplied: (saving: string) => `Offer applied · You save ${saving}`, promotionProgress: (count: number) => `Add ${count} more qualifying ${count === 1 ? "item" : "items"} to unlock the offer`, chooseFreeItem: "Choose your free item", freeRewardsAvailable: (count: number) => `${count} free ${count === 1 ? "item" : "items"} available`, addFreeItem: "Add free",
    noDescription: "No additional description is available for this item.", stockNote: "Your cart will always respect the latest available stock.", currentlyUnavailable: "Currently unavailable",
    nothingCategory: "Nothing in this category", noSearchResults: "No items found", noSearchResultsHint: "Try a different search or clear the filters to see everything.", noMerch: "No merch is live yet", switchCatalog: "Try another category or return to the full catalog.", addInAdmin: "New releases will appear here as soon as the booth adds them.", catalogEmpty: "Catalog empty", showAll: "Show all items", loadingCatalog: "Stocking the shelf", loadingCatalogHint: "Getting the latest merch and availability…", catalogUnavailable: "We couldn’t load the shelf", catalogUnavailableHint: "Check your connection and try again. Your cart is still safe on this device.", tryAgain: "Try again", loadMore: "Load more", loadingMore: "Loading…", itemsShown: (count: number) => `${count} items shown`,
    paymentComplete: "Payment complete", allSet: "You’re all set!", reservedPickup: "Staff confirmed your payment and the items are now reserved for pickup.", totalPaid: "Total paid", backShop: "Back to the shop",
    confirmOrder: "Confirm your order", lastCheck: "One last check", reviewCart: "Review your cart and add the name staff should call at pickup.", total: "Total", pickupName: "Pickup name", pickupPlaceholder: "e.g. Huy or Alice", pickupHint: "Use a name you can easily hear at the booth.", secureCheck: "Price and stock are checked securely before your order is created.", keepShopping: "Keep shopping", checking: "Checking…", createPay: "Create order & pay",
    scanPay: "Scan to pay", exactNote: "Use the exact transfer note shown below.", waitingConfirmation: "Waiting for staff confirmation", orderCode: "Order code", transferTo: "Transfer to", accountName: "Account name", accountNumber: "Account number", bank: "Bank", transferNote: "Transfer note", orderSummary: "Order summary",
    retryOrder: "Retry safely", reconnectingOrder: "Updating order status…", offlineOrder: "Offline — status will update when connected", offlineEventOrder: "Event order saved on this booth device", orderStatusError: "Couldn’t refresh order status", retryOrderStatus: "Retry status check", hidePayment: "Hide payment details", pendingOrder: "Pending order", viewPayment: "View payment", pendingOrderHint: "Your order stays active if you close this window.", orderCancelled: "Order cancelled", cancelledPaymentNote: "Staff cancelled this order. Please do not send payment for it.",
    reservedFor: (time: string) => `Reserved for ${time}`, reservedWhilePaying: "Your items are reserved while you complete payment.", offlineEventReserved: "Reserved from this booth device’s event stock.", cancelOrder: "Cancel order", cancelling: "Cancelling…", qrUnavailable: "Payment QR is unavailable. Please ask booth staff for help.", amountLabel: "Amount",
    demoCheckout: "Demo cart only", demoCheckoutTitle: "Checkout is disabled in this demo", demoCheckoutMessage: "This sample shop is for browsing and testing the cart. Open a live booth to place an order.",
    socialQrTitle: (platform: string) => `${platform} Link`, openSocialProfile: "Open Profile Link", socialQrAlt: (platform: string) => `${platform} QR code`, socialQrCodes: "Social QR codes",
    playGacha: "Play shelf wishes", playGachaHint: "A free merch minigame", backToStore: "Back to store", wishUnavailable: "The wish shelf is resting", wishUnavailableHint: "This shop has not opened its free minigame yet.", wishPoolEmptyHint: "The shop is preparing characters and weapons. Check back soon.",
    chooseGachaEyebrow: "Matsuri gacha", chooseGachaTitle: "Choose your universe", chooseGachaHint: "Pick a style. Pull booth merch.", enterGacha: "Enter", wishSimulator: "Wish simulator", warpSimulator: "Warp simulator", enterWish: "Enter wish simulator", enterWarp: "Enter warp simulator", gachaBannerCount: (count: number) => `${count} ${count === 1 ? "banner" : "banners"}`, gachaPrizeCount: (count: number) => `${count} ${count === 1 ? "prize" : "prizes"}`, saveBothGachaOffline: "Save offline", saveBothGachaOfflineHint: "Downloads both simulators and their merch artwork in one go.", savingGachaOffline: "Saving games…", gachaOfflineReady: "Offline ready", gachaOfflineFailed: "Download paused. Check the connection and try again.",
    boothGuide: "Booth guide", openNowUntil: (time: string) => `Open now · until ${time}`, closedOpensAt: (time: string) => `Closed · opens ${time}`, hoursNotSet: "Hours not set", boothDetails: "Booth details", shoppingAt: "You’re shopping at", boothCode: (code: string) => `Booth ${code}`, location: "Location", openHours: "Open hours", notSpecified: "Not specified", independentMerchBooth: "Independent merch booth", beforePay: "Before you pay", findOnline: "Find us online", followBooth: "Follow the booth",
    availableCapped: (count: number) => `${count}+ available`, removeItem: (name: string) => `Remove ${name} from cart`, decreaseQuantity: (name: string) => `Decrease ${name} quantity`, increaseQuantity: (name: string) => `Increase ${name} quantity`, collapseCart: "Collapse cart", closeModal: "Close", cartItems: "Items in your cart", scrollCartItems: "Scroll to review every item",
    viewModeLabel: "View mode", sortBy: "Sort by", productCategories: "Product categories", productImages: "Product images", showImage: (index: number) => `Show image ${index}`,
    featuredMerchandise: "Featured merchandise", featuredCount: (count: number) => `${count} featured ${count === 1 ? "item" : "items"}`, addFeaturedSelection: "Add front item", previousFeatured: "Previous featured item", nextFeatured: "Next featured item", showFeaturedItem: (name: string) => `Show ${name}`, currentFeaturedItem: (name: string) => `${name}, current featured item`,
    staffAccess: "Staff access", shopConnectError: "Could not connect to the shop.", openingShop: "Opening the shop…", openingShopHint: "Getting the shelves ready for you.", catalogUnavailableTitle: "Catalog unavailable", liveRefreshFailed: "Live catalog refresh failed.",
    toastSuccessTitle: "Done", toastErrorTitle: "Something went wrong", toastInfoTitle: "Notice", dismissNotification: "Dismiss notification",
    matsuriHome: "Matsuri home", artistBoothPlatform: "Artist booth platform", staffSignIn: "Staff sign in", storefrontUnavailableKicker: "404 · Storefront unavailable", unavailableTitle: "This booth", unavailableTitleAccent: "isn’t on the shelf.", unavailableLoadError: "We couldn’t reach it just now. Check your connection and try once more.", unavailableNotFound: "It may have moved, closed for the day, or the link might be out of date.", backToMatsuri: "Back to Matsuri", lookingForExample: "Looking for an example?", visitDemoBooth: "Visit the demo booth.", lostBoothNotice: "Lost booth notice", artistAlley404: "Artist Alley · Aisle 404", notHere: "not here!", storefrontMissing: "Storefront missing", nothingOnShelf: "nothing on this shelf", emptyDisplay: "EMPTY DISPLAY", tryAnotherAisle: "Try another aisle", booth404: "404 BOOTH", linkNotFound: "Link not found", boothDirectory: "Booth directory", noBoothFound: "No booth found", tryAnotherLink: "Try another link", keepLooking: "KEEP LOOKING", madeForArtists: "Made for independent artists, conventions, and pop-up booths.",
    offlineTitle: "You are offline.", offlineHint: "Your cart is saved on this device. Reconnect to verify stock and continue checkout.", reconnectCheckoutTitle: "Reconnect to checkout", checkoutConnectionTitle: "Couldn’t reach checkout", checkoutConnectionHint: "Your cart is saved. The order service did not respond, so retry when you’re ready.", cartSavedOffline: "Your cart is saved locally, but stock must be verified online before payment.", checkoutUnavailableTitle: "Checkout unavailable", paymentSettingsError: "Could not load payment settings.",
    itemUnavailableTitle: "Item unavailable", soldOutToast: "This item is sold out and cannot be added to your cart.", cartLimitTitle: "Cart limit reached", cartLimitMessage: (count: number) => `Only ${count} units are available.`,
    reservationExpired: "Reservation expired", reservationExpiredHint: "Payment may have been sent after this reservation expired. Please ask booth staff for assistance.", cancelReservationTitle: "Cancel this reservation?", cancelReservationHint: "The reserved items will be released back to the shelf.", keepOrder: "Keep order", paymentQrAlt: "Payment QR code", orderSubmitError: "Failed to submit order. Please try again.",
    wishLoadFailed: "Couldn’t open the wish simulator", wishLoadError: "Could not load the minigame.",
    crashTitle: "Something went wrong at the booth", crashHint: "Please reload the page. Your cart is saved on this device.", crashReload: "Reload page",
  },
  vi: {
    all: "Tất cả", officialShop: "Gian hàng chính thức", boothInfo: "Thông tin gian hàng", boothInfoHint: "Giờ mở cửa, vị trí & mạng xã hội",
    searchItems: "Tìm sản phẩm...", searchCatalog: "Tìm trong cửa hàng", clearSearch: "Xóa tìm kiếm", recommended: "Đề xuất",
    priceLow: "Giá tăng dần", priceHigh: "Giá giảm dần", mostStock: "Còn nhiều nhất", name: "Tên", gridView: "Dạng lưới", listView: "Dạng danh sách", previousCategories: "Danh mục trước", nextCategories: "Xem thêm danh mục",
    featuredDrop: "Sản phẩm nổi bật", limitedCollection: "Bộ sưu tập giới hạn", specialRelease: "Phiên bản đặc biệt tại gian hàng, chỉ bán khi còn hàng.", noFeatured: "Chưa có sản phẩm nổi bật", noFeaturedHint: "Các sản phẩm được gian hàng tuyển chọn sẽ xuất hiện tại đây.",
    inStock: "Còn hàng", onlyLeft: (count: number) => `Chỉ còn ${count}`, addToCart: "Thêm vào giỏ", swipeToBrowse: "Vuốt để xem",
    featured: "Nổi bật", sale: "Giảm giá", soldOut: "Hết hàng", available: (count: number) => `Còn ${count} sản phẩm`, unavailable: "Không khả dụng",
    viewDetails: (name: string) => `Xem chi tiết ${name}`, addProduct: (name: string) => `Thêm ${name} vào giỏ`, productSoldOut: (name: string) => `${name} đã hết hàng`,
    cart: "Giỏ hàng", emptyCart: "Giỏ hàng đang trống", emptyCartHint: "Chạm vào sản phẩm để thêm vào giỏ.", viewCart: "Xem giỏ hàng", clearAll: "Xóa tất cả", cartDockTitle: (count: number) => `${count} sản phẩm trong giỏ`, cartDockHint: "Giỏ hàng luôn ở gần khi bạn tiếp tục xem sản phẩm.",
    totalPrice: "Tổng tiền", payNow: "Thanh toán", itemDetails: "Chi tiết sản phẩm", featuredItem: "Sản phẩm nổi bật", item: "Mã", price: "Giá", discount: "Giảm giá khuyến mãi",
    buyXGetY: (buy: number, free: number) => `Mua ${buy}, tặng ${free}`, qualifyingPromotion: (buy: number) => `Tính vào mốc mua ${buy}`, rewardPromotion: "Có thể chọn miễn phí", combinedPromotion: (buy: number, free: number) => `Mua ${buy}, chọn ${free} miễn phí`, freeItems: (count: number) => `Tặng ${count}`, promotionApplied: (saving: string) => `Đã áp dụng ưu đãi · Tiết kiệm ${saving}`, promotionProgress: (count: number) => `Thêm ${count} sản phẩm mua để nhận ưu đãi`, chooseFreeItem: "Chọn sản phẩm miễn phí", freeRewardsAvailable: (count: number) => `Có ${count} sản phẩm miễn phí`, addFreeItem: "Thêm miễn phí",
    noDescription: "Sản phẩm này chưa có mô tả chi tiết.", stockNote: "Giỏ hàng luôn được đối chiếu với số lượng tồn kho mới nhất.", currentlyUnavailable: "Hiện không khả dụng",
    nothingCategory: "Không có sản phẩm trong danh mục", noSearchResults: "Không tìm thấy sản phẩm", noSearchResultsHint: "Hãy thử từ khóa khác hoặc xóa bộ lọc để xem tất cả sản phẩm.", noMerch: "Chưa có sản phẩm được mở bán", switchCatalog: "Hãy thử danh mục khác hoặc quay lại toàn bộ sản phẩm.", addInAdmin: "Sản phẩm mới sẽ xuất hiện tại đây ngay khi gian hàng cập nhật.", catalogEmpty: "Gian hàng trống", showAll: "Xem tất cả", loadingCatalog: "Đang xếp hàng lên kệ", loadingCatalogHint: "Đang tải sản phẩm và số lượng mới nhất…", catalogUnavailable: "Không thể tải gian hàng", catalogUnavailableHint: "Hãy kiểm tra kết nối và thử lại. Giỏ hàng vẫn được lưu trên thiết bị này.", tryAgain: "Thử lại", loadMore: "Xem thêm", loadingMore: "Đang tải…", itemsShown: (count: number) => `Đang hiển thị ${count} sản phẩm`,
    paymentComplete: "Thanh toán hoàn tất", allSet: "Xong rồi!", reservedPickup: "Staff đã xác nhận thanh toán và giữ sản phẩm để bạn đến nhận.", totalPaid: "Đã thanh toán", backShop: "Quay lại cửa hàng",
    confirmOrder: "Xác nhận đơn hàng", lastCheck: "Kiểm tra lần cuối", reviewCart: "Kiểm tra giỏ hàng và nhập tên để staff gọi khi nhận hàng.", total: "Tổng cộng", pickupName: "Tên nhận hàng", pickupPlaceholder: "Ví dụ: Huy hoặc Alice", pickupHint: "Dùng tên bạn có thể dễ dàng nghe thấy tại gian hàng.", secureCheck: "Giá và tồn kho được kiểm tra an toàn trước khi tạo đơn.", keepShopping: "Tiếp tục mua", checking: "Đang kiểm tra…", createPay: "Tạo đơn & thanh toán",
    scanPay: "Quét mã để thanh toán", exactNote: "Vui lòng dùng đúng nội dung chuyển khoản bên dưới.", waitingConfirmation: "Đang chờ staff xác nhận", orderCode: "Mã đơn", transferTo: "Chuyển khoản đến", accountName: "Tên tài khoản", accountNumber: "Số tài khoản", bank: "Ngân hàng", transferNote: "Nội dung chuyển khoản", orderSummary: "Chi tiết đơn hàng",
    retryOrder: "Thử lại an toàn", reconnectingOrder: "Đang cập nhật trạng thái đơn…", offlineOrder: "Đang ngoại tuyến — trạng thái sẽ cập nhật khi có mạng", offlineEventOrder: "Đơn sự kiện đã được lưu trên thiết bị của gian hàng", orderStatusError: "Không thể cập nhật trạng thái đơn", retryOrderStatus: "Kiểm tra lại trạng thái", hidePayment: "Ẩn thông tin thanh toán", pendingOrder: "Đơn đang chờ", viewPayment: "Xem thanh toán", pendingOrderHint: "Đơn hàng vẫn hoạt động khi bạn đóng cửa sổ này.", orderCancelled: "Đơn đã bị hủy", cancelledPaymentNote: "Staff đã hủy đơn này. Vui lòng không chuyển khoản cho đơn.",
    reservedFor: (time: string) => `Giữ hàng trong ${time}`, reservedWhilePaying: "Sản phẩm được giữ trong lúc bạn hoàn tất thanh toán.", offlineEventReserved: "Sản phẩm được giữ từ tồn kho sự kiện trên thiết bị gian hàng này.", cancelOrder: "Hủy đơn hàng", cancelling: "Đang hủy…", qrUnavailable: "Không thể tải mã thanh toán. Vui lòng nhờ staff tại gian hàng hỗ trợ.", amountLabel: "Số tiền",
    demoCheckout: "Chỉ thử giỏ hàng", demoCheckoutTitle: "Demo này không hỗ trợ thanh toán", demoCheckoutMessage: "Cửa hàng mẫu dùng để xem sản phẩm và thử giỏ hàng. Hãy mở một gian hàng thật để đặt đơn.",
    socialQrTitle: (platform: string) => `Liên kết ${platform}`, openSocialProfile: "Mở liên kết trang cá nhân", socialQrAlt: (platform: string) => `Mã QR ${platform}`, socialQrCodes: "Mã QR mạng xã hội",
    playGacha: "Chơi gacha kệ hàng", playGachaHint: "Minigame merch miễn phí", backToStore: "Về cửa hàng", wishUnavailable: "Kệ điều ước đang nghỉ", wishUnavailableHint: "Gian hàng này chưa mở minigame miễn phí.", wishPoolEmptyHint: "Gian hàng đang chuẩn bị nhân vật và vũ khí. Hãy quay lại sau.",
    chooseGachaEyebrow: "Matsuri gacha", chooseGachaTitle: "Chọn vũ trụ của bạn", chooseGachaHint: "Chọn phong cách. Rút merch.", enterGacha: "Vào game", wishSimulator: "Cầu Nguyện", warpSimulator: "Bước Nhảy", enterWish: "Vào Cầu Nguyện", enterWarp: "Vào Bước Nhảy", gachaBannerCount: (count: number) => `${count} banner`, gachaPrizeCount: (count: number) => `${count} phần thưởng`, saveBothGachaOffline: "Lưu ngoại tuyến", saveBothGachaOfflineHint: "Tải cả hai trình mô phỏng và hình merch trong một lần.", savingGachaOffline: "Đang lưu game…", gachaOfflineReady: "Đã sẵn sàng ngoại tuyến", gachaOfflineFailed: "Tải xuống đã dừng. Hãy kiểm tra kết nối và thử lại.",
    boothGuide: "Thông tin gian hàng", openNowUntil: (time: string) => `Đang mở · đến ${time}`, closedOpensAt: (time: string) => `Đã đóng · mở lúc ${time}`, hoursNotSet: "Chưa đặt giờ mở cửa", boothDetails: "Chi tiết gian hàng", shoppingAt: "Bạn đang mua tại", boothCode: (code: string) => `Gian ${code}`, location: "Vị trí", openHours: "Giờ mở cửa", notSpecified: "Chưa thiết lập", independentMerchBooth: "Gian hàng merch độc lập", beforePay: "Trước khi thanh toán", findOnline: "Tìm chúng tôi online", followBooth: "Theo dõi gian hàng",
    availableCapped: (count: number) => `Còn ${count}+ sản phẩm`, removeItem: (name: string) => `Xóa ${name} khỏi giỏ`, decreaseQuantity: (name: string) => `Giảm số lượng ${name}`, increaseQuantity: (name: string) => `Tăng số lượng ${name}`, collapseCart: "Thu gọn giỏ hàng", closeModal: "Đóng", cartItems: "Sản phẩm trong giỏ", scrollCartItems: "Cuộn để kiểm tra tất cả sản phẩm",
    viewModeLabel: "Chế độ xem", sortBy: "Sắp xếp theo", productCategories: "Danh mục sản phẩm", productImages: "Hình ảnh sản phẩm", showImage: (index: number) => `Xem hình ${index}`,
    featuredMerchandise: "Sản phẩm nổi bật", featuredCount: (count: number) => `${count} sản phẩm nổi bật`, addFeaturedSelection: "Thêm sản phẩm phía trước", previousFeatured: "Sản phẩm nổi bật trước", nextFeatured: "Sản phẩm nổi bật tiếp theo", showFeaturedItem: (name: string) => `Xem ${name}`, currentFeaturedItem: (name: string) => `${name}, sản phẩm nổi bật hiện tại`,
    staffAccess: "Kênh staff", shopConnectError: "Không thể kết nối đến gian hàng.", openingShop: "Đang mở gian hàng…", openingShopHint: "Đang chuẩn bị kệ hàng cho bạn.", catalogUnavailableTitle: "Không thể tải gian hàng", liveRefreshFailed: "Không thể cập nhật gian hàng trực tiếp.",
    toastSuccessTitle: "Hoàn tất", toastErrorTitle: "Đã xảy ra lỗi", toastInfoTitle: "Thông báo", dismissNotification: "Đóng thông báo",
    matsuriHome: "Trang chủ Matsuri", artistBoothPlatform: "Nền tảng gian hàng artist", staffSignIn: "Staff đăng nhập", storefrontUnavailableKicker: "404 · Gian hàng không khả dụng", unavailableTitle: "Gian hàng này", unavailableTitleAccent: "không có trên kệ.", unavailableLoadError: "Hiện chúng tôi chưa thể kết nối. Hãy kiểm tra mạng và thử lại.", unavailableNotFound: "Gian hàng có thể đã chuyển, tạm đóng hoặc liên kết đã cũ.", backToMatsuri: "Về Matsuri", lookingForExample: "Bạn muốn xem gian hàng mẫu?", visitDemoBooth: "Ghé gian hàng demo.", lostBoothNotice: "Thông báo thất lạc gian hàng", artistAlley404: "Khu Artist Alley · Dãy 404", notHere: "không ở đây!", storefrontMissing: "Không tìm thấy gian hàng", nothingOnShelf: "kệ hàng đang trống", emptyDisplay: "KỆ TRƯNG", tryAnotherAisle: "Thử dãy khác", booth404: "GIAN 404", linkNotFound: "Không tìm thấy liên kết", boothDirectory: "Danh bạ gian hàng", noBoothFound: "Không tìm thấy gian", tryAnotherLink: "Thử liên kết khác", keepLooking: "TIẾP TỤC TÌM", madeForArtists: "Dành cho artist độc lập, sự kiện và gian hàng pop-up.",
    offlineTitle: "Bạn đang ngoại tuyến.", offlineHint: "Giỏ hàng vẫn được lưu trên thiết bị này. Hãy kết nối lại để xác minh tồn kho và tiếp tục thanh toán.", reconnectCheckoutTitle: "Kết nối lại để thanh toán", checkoutConnectionTitle: "Không thể kết nối dịch vụ thanh toán", checkoutConnectionHint: "Giỏ hàng vẫn được lưu. Dịch vụ đặt đơn chưa phản hồi, hãy thử lại khi bạn sẵn sàng.", cartSavedOffline: "Giỏ hàng đã được lưu trên thiết bị này, nhưng cần xác minh tồn kho trực tuyến trước khi thanh toán.", checkoutUnavailableTitle: "Không thể mở thanh toán", paymentSettingsError: "Không thể tải cài đặt thanh toán.",
    itemUnavailableTitle: "Sản phẩm không khả dụng", soldOutToast: "Sản phẩm này đã hết hàng nên không thể thêm vào giỏ.", cartLimitTitle: "Đã đạt giới hạn giỏ hàng", cartLimitMessage: (count: number) => `Chỉ còn ${count} sản phẩm.`,
    reservationExpired: "Đơn giữ hàng đã hết hạn", reservationExpiredHint: "Có thể bạn đã chuyển khoản sau khi đơn giữ hàng hết hạn. Vui lòng nhờ staff tại gian hàng hỗ trợ.", cancelReservationTitle: "Hủy đơn giữ hàng này?", cancelReservationHint: "Các sản phẩm đang giữ sẽ được trả lại kệ.", keepOrder: "Giữ đơn hàng", paymentQrAlt: "Mã QR thanh toán", orderSubmitError: "Không thể gửi đơn hàng. Vui lòng thử lại.",
    wishLoadFailed: "Không thể mở kệ điều ước", wishLoadError: "Không thể tải minigame.",
    crashTitle: "Gian hàng gặp lỗi bất ngờ", crashHint: "Hãy tải lại trang. Giỏ hàng vẫn được lưu trên thiết bị này.", crashReload: "Tải lại trang",
  },
} as const;

export type CatalogCopy = (typeof translations)["en"] | (typeof translations)["vi"];
const CatalogLocaleContext = createContext<CatalogCopy>(translations.en);

export function CatalogLocaleProvider({ locale, children }: { locale: CatalogLocale; children: ReactNode }) {
  useEffect(() => {
    document.documentElement.lang = locale;
    return () => { document.documentElement.lang = "en"; };
  }, [locale]);
  return <CatalogLocaleContext.Provider value={translations[locale]}>{children}</CatalogLocaleContext.Provider>;
}

export function useCatalogCopy() {
  return useContext(CatalogLocaleContext);
}
